I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gui.rpy", line 166, in script
    define gui.button_text_font = gui/Ubuntu-R.ttf
  File "game/gui.rpy", line 166, in <module>
    define gui.button_text_font = gui/Ubuntu-R.ttf
NameError: name 'Ubuntu' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/gui.rpy", line 166, in script
    define gui.button_text_font = gui/Ubuntu-R.ttf
  File "D:\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 2508, in execute
    self.set()
  File "D:\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/gui.rpy", line 166, in <module>
    define gui.button_text_font = gui/Ubuntu-R.ttf
NameError: name 'Ubuntu' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
About Faces 0.1
Tue Dec 19 12:29:40 2023
